spring:
  datasource:
    username: root
    password: 354719
    url: jdbc:mysql://47.100.126.191:3306/xuxiaonan?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  port: 8080
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: X-Forwarded-Port
    #其它设置是让Tomcat去Http头信息去获取协议信息，而不是从HttpServletRequest
    internal-proxies: 192\.168\.\d{1,3}\.\d{1,3}


